config/routes.rb
Rails.application.routes.draw do

  resources :categories do
    resources :recipes, except: [:index]
  end

  get 'recipes/index'
resources :recipes
  devise_for :users

  get 'welcome/index'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes, dependent: :destroy
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :category
  has_one_attached :photo

  validates :title, presence: true
  validates :photo, presence: true
  validates :ingredient, presence: true
  validates :body,presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new
    @category.name = params[:category][:name]

    if @category.save
      redirect_to @category, notice: "Category saved successfully."
    else
      flash.now[:alert] = "There was a problem saving the category. Please try again."
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.name = params[:category][:name]

    if @category.save
      flash[:notice] = "Category was saved successfully."
      redirect_to @category
    else
      flash.now[:alert] = "There was a problem saving the category. Please try again."
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])

    if @category.destroy
      flash[:notice] = "\"#{@category.name}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the category."
      render :show
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def create
    @recipe = Recipe.find(params[:recipe_id])
    ingredient = @recipe.ingredients.new(ingredient_params)

    if ingredient.save
      redirect_to @recipe
    else
      flash.now[:notice] = "Ingredient failed to save. Please try again."
      redirect_to @recipe
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    ingredient = @recipe.ingredients.find(params[:id])

    if ingredient.destroy
      redirect_to @recipe
    else
      flash.now[:notice] = "Ingredient couldn't be deleted. Please try again."
      redirect_to @recipe
    end
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:body)
  end 

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @q = Recipe.ransack(params[:q])
    @recipes = @q.result(distinct: true)
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @category = Category.find(params[:category_id])
    @recipe = Recipe.new
  end

  def create
    @category = Category.find(params[:category_id])
    @recipe = Recipe.new
    @recipe.title = params[:recipe][:title]
    @recipe.photo = params[:recipe][:photo]
    @recipe.ingredient = params[:recipe][:ingredient]
    @recipe.body = params[:recipe][:body]

    @recipe.category = @category

    if @recipe.save
      flash[:notice] = "Recipe was saved."
      redirect_to [@category, @recipe]
    else
      flash.now[:alert] = "There was an error saving the recipe. Please try again."
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.title = params[:recipe][:title]
    @recipe.photo = params[:recipe][:photo]
    @recipe.ingredient = params[:recipe][:ingredient]
    @recipe.body = params[:recipe][:body]

    if @recipe.save
      flash[:notice] = "Recipe was updated."
      redirect_to [@recipe.category, @recipe]
    else
      flash.now[:alert] = "There was an error updating the recipe. Please try again."
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    if @recipe.destroy
      flash[:notice] = "Recipe was deleted successfully."
      redirect_to @recipe.category
    else
      flash.now[:alert] = "There was an error deleting the recipe. Please try again."
      render :show
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink: true,
      superscript: true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?

    content_tag :div, capture(&block), class: css_class
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/edit.html.erb
<div class="col-md-8-offset-2">
  <h1 class="new-title">Edit Category</h1>
  <%= form_for @category do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Category name' %>
    </div>
    <%= f.submit "Save", class: 'btn btn-default' %>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="col-md-8-offset-2">
  <%= link_to "+", new_category_path, class: 'btn btn-default add', title: "Add Category" %>
  <div class="title">
    <h1>Categories</h1>
  </div>
  <div class="categories">
    <% @categories.each do |category| %>
      <h3><%= link_to category.name, category %></h3>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="col-md-8-offset-2">
  <h1 class="new-title">New Category</h1>
  <%= form_for @category do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Category name' %>
    </div>

    <%= f.submit "Save", class: 'btn btn-default' %>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="col-md-8-offset-2">
  <%= link_to "+", new_category_recipe_path(@category), class: 'btn btn-default add', title: "Add Recipe" %>

  <h1><%= @category.name %></h1>
  <div class="edit-delete">
    <%= link_to "Edit Category", edit_category_path, class: 'btn btn-default' %>
    <%= link_to "Delete Category", @category, method: :delete, class: 'btn btn-danger' %>
  </div>
  <div class="recipes">
    <% @category.recipes.each do |recipe| %>
      <%= render partial: 'recipes/recipe', locals: { recipe: recipe } %>
    <% end %>
  </div>
</div>

app/views/ingredients/_form.html.erb
<br>
<div>
  <h4>Add ingredient</h4>
  <%= form_for [recipe, ingredient] do |f| %>
    <div class="form-group">
      <%= f.label :body, class: 'sr-only' %>
      <%= f.text_field :body, class: 'form-control', placeholder: "Ingredient" %>
    </div>
    <%= f.submit "+", class: 'btn btn-primary pull-right' %>
  <% end %>
</div>

app/views/ingredients/_ingredient.html.erb
<p><%= ingredient.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCookbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="signin">
      <% if user_signed_in? %>
        Signed in as: <strong><%= current_user.email %></strong> |
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Categories", categories_path %></li>
      <li><%= link_to "Recipe Index", recipes_index_path %></li>
    </ul>
    <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for [category, recipe] do |f| %>
  <% if recipe.errors.any? %>
    <div class="alert alert-danger">
      <p><%= pluralize(recipe.errors.count, "error") %>.</p>
      <ul>
        <% recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(recipe.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Recipe title" %>
  <% end %>
  <br>
  <%= form_group_tag(recipe.errors[:photo]) do %>
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  <% end %>
  <br>
  <%= form_group_tag(recipe.errors[:ingredient]) do %>
    <%= f.label :ingredients %>
    <%= f.text_area :ingredient, rows: 8, class: 'form-control', placeholder: "Ingredients" %>
  <% end %>
  <br>
  <%= form_group_tag(recipe.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Instructions" %>
  <% end %>
  <br>
  <%= f.submit "Save", class: "btn btn-default" %>
<% end %>

app/views/recipes/_recipe.html.erb
    <h4>
      <%= link_to recipe.title, category_recipe_path(recipe.category, recipe) %>
    </h4>

app/views/recipes/_search.html.erb
<div class="search">
  <%= search_form_for @q do |f| %>
    <%= f.search_field :title_cont, class:"search-input" %>
    <%= f.submit "Search", class: "btn btn-default" %>
  <% end %>
</div>

<table class="search-results">
  <tbody>
    <% if params[:q].present? %>
      <% @recipes.each do |recipe| %>
        <tr>
          <td class="search-result">
            <h4><%=link_to recipe.title, recipe %></h4>
          </td>
        </tr>
      <% end %>
      <% end %>
  </tbody>
</table>

app/views/recipes/edit.html.erb
<div class="col-md-8-offset-2">
  <h1 class="new-title">Edit Recipe</h1>
  <%= render partial: 'form', locals: { category: @recipe.category, recipe: @recipe } %>
</div>

app/views/recipes/index.html.erb
<div class="col-md-8-offset-2">
  <h1>
    All Recipes
  </h1>

    <%= render partial: 'search', locals: { recipe: @recipe}  %>

    <% if !params[:q] %>
  <div class="all-recipes">
    <% @recipes.each do |recipe| %>
      <h4><%= link_to recipe.title, recipe %></h4>
    <% end %>
  <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="col-md-8-offset-2">
  <h1 class="new-title">New Recipe</h1>
  <%= render partial: 'form', locals: { category: @category, recipe: @recipe } %>

</div>

app/views/recipes/show.html.erb
<div class="col-md-8-offset-2">
  <h1><%= markdown(@recipe.title) %></h1>
  <div class="edit-delete">
    <%= link_to "Edit", edit_category_recipe_path(@recipe), class: 'btn btn-default' %>
    <%= link_to "Delete", [@recipe.category, @recipe], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this recipe?'} %>
  </div>

  <% if @recipe.photo.attached? %>
    <div class="recipe-photo">
      <image class="photo" src="<%= (url_for(@recipe.photo)) %>">
    </div>
<% end %>

  <h3 class="recipes">Ingredients:</h3>
  <p><%= markdown(@recipe.ingredient) %></p>

  <h3>Instructions</h3>
  <p><%= markdown(@recipe.body) %></p>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron landing">
  <h1 class="linkit">myCookbook</h1>
  <p>Save and organize your favorite recipes</p>
</div>

<div class="row landing">
  <div class="home home-left col-md-4">
    <h2>Create</h2>
    <p>Save your recipe and upload a photo of your creation</p>
  </div>
  <div class="home center-card col-md-4">
    <h2>Search</h2>
    <p>Find your favorite recipe quickly without scrolling</p>
  </div>
  <div class="home home-right col-md-4">
    <h2>Organize</h2>
    <p>Group your recipes into categories of your choosing</p>
  </div>
</div>